language: cpp

git:
  depth: false

cache:
  directories:
    - "$HOME"'/vcpkg'

matrix:
  include:
    - os: linux
      sudo: true
      env:
        - VCPKG_TRIPLET='x64-linux'
        - MATRIX_EVAL='export CC=gcc-8 && export CXX=g++-8'
        - VCPKG_BOOT_EVAL=./'bootstrap-vcpkg.sh'
        - SYSTEM_TRIPLET='linux'
        - PREFERED_ARCHIVE_EXTENSION='tar.gz'
        - LIBOFFKV_CMAKE_FLAGS=''
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL='brew install gcc@7'
        - OSX_ENABLE_GCC='CC=gcc-7 && CXX=g++-7'
        - OSX_ENABLE_CLANG='CC=clang && CXX=clang++'
        - VCPKG_BOOT_EVAL='./bootstrap-vcpkg.sh'
        - SYSTEM_TRIPLET='darwin'
        - PREFERED_ARCHIVE_EXTENSION='zip'
        - LIBOFFKV_CMAKE_FLAGS=''
      sudo: true
    # - os: windows
    #   env:
    #     - VCPKG_TRIPLET=x64-windows
    #     - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.bat"
    #     - SYSTEM_TRIPLET=windows
    #     - PREFERED_ARCHIVE_EXTENSION=zip

before_install:
  - eval "${MATRIX_EVAL}"
  - eval "$OSX_ENABLE_GCC"

before_script:
  - git clone --depth=1 'https://github.com/offscale/kv-travis-scripts' "$HOME"'/travis'
  - chmod ug+x "$HOME"'/travis'/*.sh
  - "$HOME"'/travis/prepare_vcpkg.sh' "$HOME"'/vcpkg/' "${VCPKG_BOOT_EVAL}"
  - cp -r "$TRAVIS_BUILD_DIR"'/vcpkg/ports' "$HOME"'/vcpkg/'
  - cd "$HOME"'/vcpkg'
  - travis_wait 30 ./vcpkg upgrade --no-dry-run
  - eval "$OSX_ENABLE_CLANG"
  - travis_wait 25 ./vcpkg install gtest || "$HOME"'/travis/export_vcpkg_logs.sh'
  - travis_wait 34 ./vcpkg install ppconsul || "$HOME"'/travis/export_vcpkg_logs.sh'
  - travis_wait 25 ./vcpkg install zkpp || "$HOME"'/travis/export_vcpkg_logs.sh'
  - travis_wait 35 ./vcpkg install offscale-libetcd-cpp || "$HOME"'/travis/export_vcpkg_logs.sh'
  - rm -rf 'buildtrees'

script:
  - mkdir "$TRAVIS_BUILD_DIR"'/cmake-build-debug' && cd "$TRAVIS_BUILD_DIR"'/cmake-build-debug'
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="$HOME"'/vcpkg/scripts/buildsystems/vcpkg.cmake' -DBUILD_TESTS=ON "${LIBOFFKV_CMAKE_FLAGS}" ..
  - cmake --build .
  - "$HOME"'/travis/bootstrap_etcd.sh' "$SYSTEM_TRIPLET" "$PREFERED_ARCHIVE_EXTENSION"
  - "$HOME"'/travis/bootstrap_consul.sh' "$SYSTEM_TRIPLET"
  - "$HOME"'/travis/bootstrap_zk.sh'
  - ctest --verbose

after_failure:
  - "$HOME"'/travis/send_status_message.sh'
