language: cpp

git:
  depth: false

cache:
  directories:
    - $HOME/vcpkg

matrix:
  include:
    - os: windows
      env:
        - MATRIX_EVAL='choco install visualstudio2019community && VS160COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"'
        - VCPKG_TRIPLET=x64-windows
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.bat"
        - SYSTEM_TRIPLET=windows
        - PREFERED_ARCHIVE_EXTENSION=zip
        - LIBOFFKV_CMAKE_FLAGS="-DENABLE_ETCD=OFF -DENABLE_ZK=OFF"
        - SYSTEM_CMAKE_FLAGS='-G "Visual Studio 16 2019"'

before_install:
  - eval "${MATRIX_EVAL}"
  - eval "$OSX_ENABLE_GCC"

before_script:
  - echo "$VS160COMNTOOLS"
  - chmod ug+x $TRAVIS_BUILD_DIR/travis/*.sh
  - $TRAVIS_BUILD_DIR/travis/prepare_vcpkg.sh "$HOME/vcpkg/" "${VCPKG_BOOT_EVAL}"
  - cp -r "$TRAVIS_BUILD_DIR/vcpkg/ports" "$HOME/vcpkg/"
  - cd "$HOME/vcpkg"
  - travis_wait 30 ./vcpkg upgrade --no-dry-run
  - eval "$OSX_ENABLE_CLANG"
  - travis_wait 25 ./vcpkg install gtest || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh
  - travis_wait 34 ./vcpkg install ppconsul || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh
  - CMAKE_PATH=$($TRAVIS_BUILD_DIR/travis/locate_vcpkg_cmake.sh "$HOME/vcpkg")
  - export PATH="$PATH:$CMAKE_PATH"
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_wait 25 ./vcpkg install zkpp || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_wait 35 ./vcpkg install etcdcpp || $TRAVIS_BUILD_DIR/travis/export_vcpkg_logs.sh; fi
  - rm -rf buildtrees

script:
  - mkdir "$TRAVIS_BUILD_DIR/cmake-build-debug" && cd "$TRAVIS_BUILD_DIR/cmake-build-debug"
  - "${CMAKE_PATH}/cmake" ${SYSTEM_CMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" -DBUILD_TESTS=ON ${LIBOFFKV_CMAKE_FLAGS} ..
  - "${CMAKE_PATH}/cmake" --build .
  - $TRAVIS_BUILD_DIR/travis/bootstrap_etcd.sh "$SYSTEM_TRIPLET" "$PREFERED_ARCHIVE_EXTENSION"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_consul.sh "$SYSTEM_TRIPLET"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_zk.sh
  - ctest --verbose

after_failure:
  - $TRAVIS_BUILD_DIR/travis/send_status_message.sh
