language: cpp

git:
  depth: false

matrix:
  include:
    - os: linux
      sudo: true
      env:
        - VCPKG_TRIPLET=x64-linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
    - os: osx
      osx_image: xcode10.2
      sudo: true
    - os: windows

before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then  brew install gcc@7 || brew link --overwrite gcc@7; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      git clone https://github.com/Microsoft/vcpkg --depth=20 "%HOME%\vcpkg";
      cd "%HOME%\vcpkg";
      bootstrap-vcpkg.bat;
      .\vcpkg integrate install;
      cd "%TRAVIS_BUILD_DIR%";
      md cmake-build-debug;
      cd cmake-build-debug;
    else
      git clone https://github.com/Microsoft/vcpkg --depth=20 "$HOME/vcpkg";
      cd "$HOME/vcpkg";
      ./bootstrap-vcpkg.sh;
      ./vcpkg integrate install;
      cd "$TRAVIS_BUILD_DIR";
      mkdir cmake-build-debug && cd "$_"
    fi
  - vcpkg install ppconsul etcdpp zkpp;
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="<replace with path to vcpkg.cmake>" -DBUILD_TESTS=ON ..;
  - cmake --build .;
  - ctest;
