language: cpp

git:
  depth: false

matrix:
  include:
    - os: linux
      sudo: true
      env:
        - VCPKG_TRIPLET=x64-linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
    - os: osx
      osx_image: xcode10.2
      sudo: true
    - os: windows

before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then  brew install gcc@7 || brew link --overwrite gcc@7; fi

script:
  - git clone https://github.com/Microsoft/vcpkg --depth=20 "$HOME/vcpkg" && cd "$_"
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      .\bootstrap-vcpkg.bat;
      .\vcpkg integrate install;
    else
      cd "$HOME/vcpkg";
      ./bootstrap-vcpkg.sh;
      ./vcpkg integrate install;
    fi
  - vcpkg install ppconsul etcdpp zkpp;
  - mkdir "$TRAVIS_BUILD_DIR/cmake-build-debug" && cd "$_"
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" -DBUILD_TESTS=ON ..;
  - cmake --build .;
  - ctest;
